openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation of contacts book
tags:
  - name: Contacts
    description: Operations with contscts
servers:
  - url: http://127.0.0.1:8080
  - url: https://contacts-g220.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: '../swagger/path/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../swagger/path/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/path/contacts/{contactId}/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/path/contacts/get.yaml'
    post:
      $ref: '../swagger/path/contacts/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
